const fs = require('fs')
const path = require('path')
const root = path.resolve(__dirname, '..', 'dist', 'win-unpacked', 'resources', 'host', 'node_modules', '@deepseek-ai', 'dsh-host-directory-picker-native', 'lib')
const w = fs.readFileSync(path.join(root, 'worker.cjs'), 'utf8')
const i = fs.readFileSync(path.join(root, 'index.js'), 'utf8')
console.log('worker stdout fallback:', w.includes('process.stdout.write(JSON.stringify(message)'))
console.log('worker conditional send:', w.includes('typeof process.send === "function"'))
console.log('index wiring:', i.includes('worker.on("message", onMessage)'))
console.log('index pipe:', i.includes('"pipe"'))
console.log('ALL PASS:', w.includes('process.stdout.write(JSON.stringify(message)') && i.includes('worker.on("message", onMessage)') && i.includes('"pipe"'))