/**
 * Chinese descriptions for official dsh plugins, keyed by the unscoped module
 * name (e.g. `dsh-llm` for `@deepseek-ai/dsh-llm`). Plugins not in this map
 * fall back to the English package.json description.
 */
export const CHINESE_DESCRIPTIONS: Record<string, string> = {
  // ── Cordis 内置插件 ──
  'cordis:group': '插件分组管理，支持条目的逻辑分组与隔离',
  'cordis:hmr': '插件热更新，开发时实时重载',
  'cordis:include': '从配置文件加载插件列表，支持 patch 叠加',
  'cordis:loader': 'Cordis 插件加载器核心，管理插件生命周期',
  'cordis:logger': '控制台日志输出',
  'cordis:timer': '定时器管理',

  // ── Cordis 基础设施 ──
  'cordis-plugin-group': '插件分组管理，支持条目的逻辑分组与隔离',
  'cordis-plugin-hmr': '插件热更新，开发时实时重载',
  'cordis-plugin-include': '从配置文件加载插件列表，支持 patch 叠加',
  'cordis-plugin-loader': 'Cordis 插件加载器核心，管理插件生命周期',
  'cordis-plugin-logger-console': '控制台日志输出',
  'cordis-plugin-timer': '定时器管理',

  // ── 核心能力 ──
  'dsh-agent': '智能体核心，管理会话与 Agent 实例',
  'dsh-agent-default-model': '默认模型配置，设置 Agent 默认使用的 LLM',
  'dsh-agent-instructions': 'Agent 指令管理，定义系统提示词与行为规则',
  'dsh-agent-loop': 'Agent 运行循环，驱动推理-工具-观察迭代',
  'dsh-agent-presets': 'Agent 预设管理，支持预设发现、加载与切换',
  'dsh-agent-tool-presentation': '工具呈现方式管理，决定工具结果如何展示',
  'dsh-anonymous-user-id': '匿名用户标识生成与管理',
  'dsh-api-gateway': 'API 网关，处理前端与 Host 的 RPC 通信',
  'dsh-api-remotes': 'Remote 服务注册与发现，跨进程 RPC 调用',
  'dsh-app-boot': '应用启动引导，加载配置树与插件集合',
  'dsh-atomic-write': '原子写入，确保文件写入的完整性',
  'dsh-attachment': '附件管理，处理文件上传与引用',
  'dsh-attachment-local': '本地附件存储实现',
  'dsh-base': '基础插件集合，包含所有核心服务的配置',
  'dsh-bash-local': '本地 Bash 执行能力',
  'dsh-bash-sandbox': '沙箱化 Bash 执行，提供安全隔离',
  'dsh-brand': '品牌标识类型，用于跨边界 ID 的类型安全',
  'dsh-client-connection': '客户端连接管理，WebSocket 通信',
  'dsh-client-hmr': '客户端热更新',
  'dsh-client-locale': '国际化（i18n）支持，提供多语言翻译',
  'dsh-client-modules': '客户端模块管理',
  'dsh-client-runtime': '客户端运行时，管理前端状态与生命周期',
  'dsh-client-schema-form': '配置表单自动生成，基于 Schema 渲染',
  'dsh-client-ui-agent-preset': 'Agent 预设选择界面',
  'dsh-client-ui-attachment': '附件上传与管理界面',
  'dsh-client-ui-commands': '命令面板界面',
  'dsh-client-ui-conversation': '对话界面，消息列表与输入',
  'dsh-client-ui-cordis': 'Cordis 调试界面',
  'dsh-client-ui-deliverables': '交付物查看界面',
  'dsh-client-ui-directory-picker-browse': '目录浏览选择器',
  'dsh-client-ui-directory-picker-native': '系统原生目录选择器',
  'dsh-client-ui-goal': '目标管理界面，展示当前任务与进度',
  'dsh-client-ui-input-trigger': '输入触发器界面，管理快捷输入',
  'dsh-client-ui-jobs': '后台任务管理界面',
  'dsh-client-ui-layout': '应用布局框架，管理侧边栏与主区域',
  'dsh-client-ui-message-feedback': '消息反馈界面，点赞/踩',
  'dsh-client-ui-model-selection': '模型选择界面',
  'dsh-client-ui-permission-presets': '权限预设管理界面',
  'dsh-client-ui-plan': '计划模式界面，展示 Agent 的思考步骤',
  'dsh-client-ui-primitives': '基础 UI 组件库，图标与通用控件',
  'dsh-client-ui-settings': '设置界面框架',
  'dsh-client-ui-settings-general': '通用设置界面',
  'dsh-client-ui-settings-models': '模型设置界面，管理 API 密钥与模型',
  'dsh-client-ui-settings-plugin-inventory': '插件列表设置界面，查看与启停插件',
  'dsh-client-ui-settings-plugins': '插件设置界面',
  'dsh-client-ui-sidebar': '侧边栏界面，会话列表与导航',
  'dsh-client-ui-skill': '技能界面',
  'dsh-client-ui-slots': '插槽系统，管理界面注册与渲染',
  'dsh-client-ui-subagent': '子 Agent 界面',
  'dsh-client-ui-theme': '主题管理界面，切换浅色/深色模式',
  'dsh-client-ui-tool': '工具调用结果展示界面',
  'dsh-client-ui-trajectory': '执行轨迹查看界面，展示推理过程',
  'dsh-client-ui-user-questions': '用户提问交互界面',
  'dsh-client-ui-workflow-run': '工作流运行界面',
  'dsh-client-ui-workspace': '工作区管理界面',
  'dsh-client-web': 'Web 客户端宿主，初始化前端应用',
  'dsh-client-web-react': 'React 渲染引擎，绑定状态与组件',
  'dsh-cmdline': '命令行界面，处理 dsh CLI 参数',
  'dsh-code-runtime': '代码执行运行时，支持多语言代码运行',
  'dsh-code-runtime-worker-thread': 'Worker 线程代码执行引擎',
  'dsh-command-compact': '会话压缩命令',
  'dsh-command-feedback': '反馈命令',
  'dsh-command-goal': '目标管理命令',
  'dsh-commands': '命令注册与分发',
  'dsh-compaction': '会话压缩，减少上下文占用',
  'dsh-compaction-basic': '基础压缩策略实现',
  'dsh-compaction-tool-result-pruner': '工具结果裁剪，压缩时移除冗余内容',
  'dsh-cordis-client-runner': '客户端 Cordis 运行时',
  'dsh-cordis-host-runner': '服务端 Cordis 运行时',
  'dsh-credentials': '凭据管理，安全存储 API 密钥',
  'dsh-credentials-local': '本地凭据存储实现，从 .env 文件读取',
  'dsh-fs': '文件系统能力定义',
  'dsh-fs-local': '本地文件系统操作实现',
  'dsh-fs-observation-policy': '文件系统观察策略，限制 Agent 可见文件',
  'dsh-fs-sandbox': '沙箱化文件系统访问',
  'dsh-goal': '目标管理，跟踪 Agent 的多轮任务',
  'dsh-goal-round-driver': '多轮目标驱动引擎',
  'dsh-headless': '无头模式，适用于自动化/CI 场景',
  'dsh-home-paths': 'DSH 主目录路径解析',
  'dsh-host-apiproxy': 'Host API 代理，处理前端请求',
  'dsh-host-directory-picker': '目录选择器服务',
  'dsh-host-directory-picker-auto': '自动目录选择器',
  'dsh-host-directory-picker-browse': '浏览目录选择器',
  'dsh-host-directory-picker-native': '系统原生目录选择器',
  'dsh-host-frontend-static': '前端静态文件服务',
  'dsh-host-plugin-inventory': '插件清单服务，提供插件列表与启停',
  'dsh-host-webserver': 'Web 服务器，提供 HTTP 服务',
  'dsh-invariants': '运行时不变式检查',
  'dsh-jobs': '后台任务管理',
  'dsh-jobs-local': '本地后台任务实现',
  'dsh-launch-environment': '启动环境配置',
  'dsh-llm': 'LLM 能力定义，大语言模型调用接口',
  'dsh-llm-deepseek': 'DeepSeek 模型提供商实现',
  'dsh-llm-pi-ai': 'pi-ai 模型提供商实现',
  'dsh-llm-retry': 'LLM 调用重试与容错',
  'dsh-mcp-client': 'MCP（Model Context Protocol）客户端',
  'dsh-message-feedback': '消息反馈收集',
  'dsh-native-command': '原生命令执行，运行宿主系统命令',
  'dsh-output-retention': '输出保留策略',
  'dsh-permission-presets': '权限预设管理',
  'dsh-persona': '角色身份管理',
  'dsh-plan-mode': '计划模式，让 Agent 先思考再行动',
  'dsh-pwsh-local': '本地 PowerShell 执行能力',
  'dsh-pwsh-sandbox': '沙箱化 PowerShell 执行',
  'dsh-repeat-tool-reminder': '重复工具调用提醒，避免无限循环',
  'dsh-sandbox': '沙箱能力定义',
  'dsh-sandbox-local': '本地沙箱实现',
  'dsh-sandbox-policy': '沙箱策略配置',
  'dsh-sandbox-windows-acl': 'Windows ACL 沙箱，安全隔离进程',
  'dsh-schedule': '任务调度',
  'dsh-scope': '作用域管理，控制插件可见性',
  'dsh-session': '会话管理，持久化对话状态',
  'dsh-session-checkpoint-policy': '会话检查点策略',
  'dsh-session-log-export': '会话日志导出',
  'dsh-session-persistence': '会话持久化，保存与恢复对话',
  'dsh-session-persistence-jsonl': 'JSONL 格式会话持久化',
  'dsh-session-persistence-sqlite': 'SQLite 格式会话持久化',
  'dsh-session-projection': '会话投影，处理会话数据结构',
  'dsh-session-projection-cache': '会话投影缓存',
  'dsh-session-query': '会话查询，搜索历史消息',
  'dsh-session-query-sqlite': 'SQLite 全文搜索会话查询',
  'dsh-session-reference': '会话引用管理',
  'dsh-session-stats': '会话统计信息',
  'dsh-session-telemetry': '会话遥测数据收集',
  'dsh-session-telemetry-otel': 'OpenTelemetry 遥测导出',
  'dsh-session-title': '会话标题生成',
  'dsh-session-title-all-prompts-llm': '基于所有提示词生成会话标题',
  'dsh-session-title-first-prompt-llm': '基于首条提示词生成会话标题',
  'dsh-session-title-llm': '基于 LLM 生成会话标题',
  'dsh-settings': '设置能力定义',
  'dsh-settings-file': '本地文件设置存储（settings.yaml）',
  'dsh-shell': 'Shell 能力定义，执行系统命令',
  'dsh-shell-env': 'Shell 环境变量管理',
  'dsh-skill': '技能管理，加载与执行 Agent 技能',
  'dsh-skill-badge': '技能徽章，标记技能元数据',
  'dsh-skill-filesystem': '基于文件系统的技能加载',
  'dsh-spill': '溢出管理，处理上下文窗口溢出',
  'dsh-spill-local': '本地溢出存储实现',
  'dsh-spill-policy': '溢出策略配置',
  'dsh-storage': '存储能力定义',
  'dsh-storage-domain': '存储域管理',
  'dsh-storage-json': 'JSON 文件存储实现',
  'dsh-storage-sqlite': 'SQLite 存储实现',
  'dsh-subagent': '子 Agent 能力定义，委托任务给子 Agent',
  'dsh-subagent-fork-in-process': '进程内分支子 Agent',
  'dsh-subagent-in-process-driver': '进程内子 Agent 驱动',
  'dsh-subagent-spawn-in-process': '进程内生成子 Agent',
  'dsh-subprocess': '子进程能力定义',
  'dsh-subprocess-local': '本地子进程实现',
  'dsh-system-prompt': '系统提示词管理',
  'dsh-terminal': '终端能力定义',
  'dsh-terminal-bash': 'Bash 终端实现',
  'dsh-time-context': '时间上下文，向 Agent 提供当前时间信息',
  'dsh-timeout': '超时管理，控制操作执行时间',
  'dsh-tmux-context': 'Tmux 上下文信息',
  'dsh-token-meter': 'Token 计数与计量',
  'dsh-tool-ask-user': '询问用户工具，向用户提问',
  'dsh-tool-bash': 'Bash 执行工具',
  'dsh-tool-bash-persistent': '持久化 Bash 会话工具',
  'dsh-tool-call-timeout-policy': '工具调用超时策略',
  'dsh-tool-cordis': 'Cordis 调试工具',
  'dsh-tool-fs': '文件系统工具，读写文件',
  'dsh-tool-fs-search': '文件搜索工具，查找文件内容',
  'dsh-tool-goal': '目标管理工具',
  'dsh-tool-jobs': '后台任务工具',
  'dsh-tool-pwsh': 'PowerShell 执行工具',
  'dsh-tool-ralph': '顺序执行工具，串联多个工具调用',
  'dsh-tool-session-query': '会话历史查询工具',
  'dsh-tool-skill': '技能执行工具',
  'dsh-tool-str-replace-editor': '字符串替换编辑器工具',
  'dsh-tool-subagent': '子 Agent 工具，委托任务',
  'dsh-tool-subagent-control': '子 Agent 控制工具',
  'dsh-tool-subagent-report': '子 Agent 报告工具',
  'dsh-tool-terminal': '终端命令执行工具',
  'dsh-tool-todo': '待办事项工具',
  'dsh-tool-web': '网页浏览工具，获取网页内容',
  'dsh-tool-workflow': '工作流执行工具',
  'dsh-tools': '工具注册与发现',
  'dsh-typert-loader': 'Typert 类型生成加载器',
  'dsh-typert-protocol': 'Typert 协议，类型安全 RPC 通信',
  'dsh-typert-registry': 'Typert 类型注册表',
  'dsh-user-approval': '用户审批，敏感操作需确认',
  'dsh-user-questions': '用户提问，Agent 向用户收集信息',
  'dsh-web': 'Web 应用启动入口',
  'dsh-web-app': 'Web 应用组合包，包含完整 Web 插件集合',
  'dsh-web-frontend': 'Web 前端静态资源',
  'dsh-web-search-deepseek': 'DeepSeek 联网搜索功能',
  'dsh-workflow': '工作流能力定义，多步骤自动化',
  'dsh-workflow-worker-thread': 'Worker 线程工作流执行引擎',
  'dsh-workspace': '工作区管理，管理项目与目录',
}
